export const ACCOUNT_GRPC_CLIENT = 'ACCOUNT_GRPC_CLIENT';
export const COMMISSION_GRPC_CLIENT = 'COMMISSION_GRPC_CLIENT';
export const CONVERTER_GRPC_CLIENT = 'CONVERTER_GRPC_CLIENT';
export const PROCESSING_KAFKA_CLIENT = 'PROCESSING_KAFKA_CLIENT';
